In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [10]:
Hz=1.5
ans=2*np.pi*Hz
x=np.arange(0,10,.1)
y=np.sin(ans*x)
z=np.cos(ans*x)

In [11]:
df=pd.DataFrame({'Time':x,'YVals':y,'ZVals':z})
df

    Time         YVals         ZVals
0    0.0  0.000000e+00  1.000000e+00
1    0.1  8.090170e-01  5.877853e-01
2    0.2  9.510565e-01 -3.090170e-01
3    0.3  3.090170e-01 -9.510565e-01
4    0.4 -5.877853e-01 -8.090170e-01
5    0.5 -1.000000e+00 -1.836970e-16
6    0.6 -5.877853e-01  8.090170e-01
7    0.7  3.090170e-01  9.510565e-01
8    0.8  9.510565e-01  3.090170e-01
9    0.9  8.090170e-01 -5.877853e-01
10   1.0  3.673940e-16 -1.000000e+00
11   1.1 -8.090170e-01 -5.877853e-01
12   1.2 -9.510565e-01  3.090170e-01
13   1.3 -3.090170e-01  9.510565e-01
14   1.4  5.877853e-01  8.090170e-01
15   1.5  1.000000e+00  5.510911e-16
16   1.6  5.877853e-01 -8.090170e-01
17   1.7 -3.090170e-01 -9.510565e-01
18   1.8 -9.510565e-01 -3.090170e-01
19   1.9 -8.090170e-01  5.877853e-01
20   2.0 -7.347881e-16  1.000000e+00
21   2.1  8.090170e-01  5.877853e-01
22   2.2  9.510565e-01 -3.090170e-01
23   2.3  3.090170e-01 -9.510565e-01
24   2.4 -5.877853e-01 -8.090170e-01
25   2.5 -1.000000e+00 -2.694842e-15
26   2.6 -5.877853e-01  8.090170e-01
27   2.7  3.090170e-01  9.510565e-01
28   2.8  9.510565e-01  3.090170e-01
29   2.9  8.090170e-01 -5.877853e-01
..   ...           ...           ...
70   7.0 -9.809554e-16 -1.000000e+00
71   7.1 -8.090170e-01 -5.877853e-01
72   7.2 -9.510565e-01  3.090170e-01
73   7.3 -3.090170e-01  9.510565e-01
74   7.4  5.877853e-01  8.090170e-01
75   7.5  1.000000e+00  9.790985e-16
76   7.6  5.877853e-01 -8.090170e-01
77   7.7 -3.090170e-01 -9.510565e-01
78   7.8 -9.510565e-01 -3.090170e-01
79   7.9 -8.090170e-01  5.877853e-01
80   8.0 -2.939152e-15  1.000000e+00
81   8.1  8.090170e-01  5.877853e-01
82   8.2  9.510565e-01 -3.090170e-01
83   8.3  3.090170e-01 -9.510565e-01
84   8.4 -5.877853e-01 -8.090170e-01
85   8.5 -1.000000e+00 -4.899206e-15
86   8.6 -5.877853e-01  8.090170e-01
87   8.7  3.090170e-01  9.510565e-01
88   8.8  9.510565e-01  3.090170e-01
89   8.9  8.090170e-01 -5.877853e-01
90   9.0  6.859260e-15 -1.000000e+00
91   9.1 -8.090170e-01 -5.877853e-01
92   9.2 -9.510565e-01  3.090170e-01
93   9.3 -3.090170e-01  9.510565e-01
94   9.4  5.877853e-01  8.090170e-01
95   9.5  1.000000e+00  8.819314e-15
96   9.6  5.877853e-01 -8.090170e-01
97   9.7 -3.090170e-01 -9.510565e-01
98   9.8 -9.510565e-01 -3.090170e-01
99   9.9 -8.090170e-01  5.877853e-01

[100 rows x 3 columns]

In [12]:
df.head()

   Time     YVals     ZVals
0   0.0  0.000000  1.000000
1   0.1  0.809017  0.587785
2   0.2  0.951057 -0.309017
3   0.3  0.309017 -0.951057
4   0.4 -0.587785 -0.809017

In [13]:
Extract_data=df[["YVals","ZVals"]][10:16]
Extract_data

           YVals         ZVals
10  3.673940e-16 -1.000000e+00
11 -8.090170e-01 -5.877853e-01
12 -9.510565e-01  3.090170e-01
13 -3.090170e-01  9.510565e-01
14  5.877853e-01  8.090170e-01
15  1.000000e+00  5.510911e-16

In [14]:
Extract_data.to_csv("out.txt")

In [15]:
alone_data=pd.read_csv("out.txt")
alone_data

   Unnamed: 0         YVals         ZVals
0          10  3.673940e-16 -1.000000e+00
1          11 -8.090170e-01 -5.877853e-01
2          12 -9.510565e-01  3.090170e-01
3          13 -3.090170e-01  9.510565e-01
4          14  5.877853e-01  8.090170e-01
5          15  1.000000e+00  5.510911e-16